### PR TITLE
Emission corrections and public keys updated for testnet

### PR DESCRIPTION
**Pull request by rsdevgun16e**

### CODE REVIEW

**Comment by yghazi** [comment]
tACK

**Comment by RyanLucchese** [comment]
[Update public keys](https://trello.com/c/WpaCyaf5/26-update-public-keys)

**Comment by RyanLucchese** [comment]
[Reset testnet data directory](https://trello.com/c/KbN4z4Xj/52-reset-testnet-data-directory)

**Comment by RyanLucchese** [comment]
[Changing coin emission and distribution](https://trello.com/c/wiBcUjg7/6-changing-coin-emission-and-distribution)

**Comment by RyanLucchese** [comment]
Fixes #92 
Fixes #75 
Fixes #79

**Pull request merged**
