### PR TITLE
Emission updates

### PR DESCRIPTION
**Pull request by yghazi**
These are the emission/budget payment changes according to the new plan:

```
There are again 525,600 blocks per year so really we need:
masternode is 30% of all coins or 3.6M / 525,600 = 6.85
mining is 20% of all coins or 2.4M / 525,600 = 4.57
foundation is 10% of all coins or 1.2M / 525,600 = 2.28

then 6.85 + 4.57 + 2.28 = 13.7 in total block emission (separate from treasury)
```

Then there are treasury changes, where there will be 26.07 superblocks in a year (after every two weeks) with a fixed limit of 184000, except the initial funding:

`(13.7 * 525600) + (184000 * 26.07) = 11,997,600`

### CODE REVIEW

**Comment by yghazi** [comment]
Jenkins test this please

**Comment by RyanLucchese** [comment]
[Proposal fee to 100EGI](https://trello.com/c/jZKjKieu/90-proposal-fee-to-100egi)

**Comment by RyanLucchese** [comment]
[14 day budget cycle](https://trello.com/c/nv8LYxzz/86-14-day-budget-cycle)

**Comment by RyanLucchese** [comment]
[Changing coin emission and distribution](https://trello.com/c/wiBcUjg7/6-changing-coin-emission-and-distribution)

**Comment by RyanLucchese** [comment]
[Initial treasury budget](https://trello.com/c/U4ORlopK/56-initial-treasury-budget)

**Pull request merged**
