### PR TITLE
#146 fix

### PR DESCRIPTION
**Pull request by levongh**

### CODE REVIEW

**Comment by levongh** [comment]
[URITests failure test_energi-qt](https://trello.com/c/gHkEV0Vv/94-uritests-failure-testenergi-qt)

**Comment by RyanLucchese** [comment]
Jenkins test this please

**Comment by narek-h** [comment]
Jenkins test this please..

**Comment by narek-h** [comment]
Jenkins test please

**Comment by RyanLucchese** [comment]
Jenkins test this please

**Comment by RyanLucchese** [comment]
Jenkins test this please

**Comment by RyanLucchese** [comment]
Jenkins test this please

**Comment by narek-h** [comment]
Jenkins test

**Comment by narek-h** [comment]
Created another PR (#179) replacing this one.

**Pull request closed without merging**
