### PR TITLE
Fix the Masternode payment amount

### PR DESCRIPTION
**Pull request by yghazi**
Fixes the amount being paid to masternodes. 

Related to #134

### CODE REVIEW

**Comment by yghazi** [comment]
[Masternode payment inconsistencies](https://trello.com/c/J9sK9c9z/84-masternode-payment-inconsistencies)

**Comment by yghazi** [comment]
test this please

**Comment by yghazi** [comment]
test this please

**Comment by RyanLucchese** [comment]
test this please

**Pull request merged**
