### PR TITLE
Consistent development environment (Phase I)

### PR DESCRIPTION
**Pull request by andvgal**
NEW: added Energi Development Environment documentation
NEW: updated autogen.sh to check & install missing dependencies for Debian-like systems
NEW: introduced optional Vagrant VM as safe fallback for development builds
NEW: added FutoIn CID-based command shortcuts:

* "cid prepare" - autogen+configure for release build
    - "cid run prepare-debug" - same, but for debug
    - "cid run prepare-profile" - same, but for debug+profile
* "cid build" - execute previously configured build
* "cid check" - runs the sub-commands below
    - "cid run check-make" - standard "make check"
    - "cid run check-rpc" - run python-based RPC test framework
* "cid package" - TODO: create release packages

NEW: GUI support for builder VM
CHANGED: to build out-of-tree-source in `./builds/{hostname}-{type}` folder with symlink from `./build/`
CHANGED: experimentally updated TravisCI config to use CID commands (may fail, to be tested)
CHANGED: added verbosity to bctest.py failures
CHANGED: mass update of Python scripts to be compatible with Python 3
CHANGED: RPCTests: changed to continue execution of tests on failure

### CODE REVIEW

**Review by levongh — DISMISSED** [review]
Looks good

**Comment by RyanLucchese** [comment]
@energicryptocurrency-jenkins Jenkins ok to test

**Comment by andvgal** [comment]
@energicryptocurrency-jenkins ok to test

**Comment by andvgal** [comment]
Closing this one in favor of GitLab PR.

**Pull request closed without merging**
