### PR TITLE
#21 fix

### PR DESCRIPTION
**Pull request by levongh**
Depends on PR #170

### CODE REVIEW

**Comment by levongh** [comment]
[QA: txn_doublespend.py test case is failing](https://trello.com/c/zB6gPmtl/34-qa-txndoublespendpy-test-case-is-failing)

**Comment by narek-h** [comment]
Jenkins test please

**Comment by narek-h** [comment]
Jenkins test please

**Comment by narek-h** [comment]
Jenkins test

**Comment by narek-h** [comment]
Jenkins test this please

**Pull request closed without merging**
