### PR TITLE
Fixed #196

### LINKED ISSUE #196: Core dump in transactions tab
Steps to reproduce
1. Open wallet energi-qt
2. Go to Transactions tab
3. right click under transactions table view

### PR DESCRIPTION
**Pull request by levongh**
Core dump in transactions tab

### CODE REVIEW

**Comment by levongh** [comment]
[Core dump in transactions tab](https://trello.com/c/Yrnz0kp2/122-core-dump-in-transactions-tab)

**Comment by RyanLucchese** [comment]
Jenkins test this please

**Comment by levongh** [comment]
Jenkins test this please

**Comment by levongh** [comment]
Jenkins test this please

**Review by RyanLucchese — APPROVED** [review]

**Pull request merged**
