### PR TITLE
Genesis Block changes for testnet and regtest

### PR DESCRIPTION
**Pull request by rsdevgun16e**

### CODE REVIEW

**Review by ankisharmadel — COMMENTED** [review]
I believe timestamp string should be a two letter word only i.e. " World Power". This is what we discussed in one of the past meeting

**Comment by yghazi** [comment]
utACK. Looks good to me. I think Anki is right, but we can always change that later.

**Comment by RyanLucchese** [comment]
[Genesis block is invalid](https://trello.com/c/V7aeKwQ3/28-genesis-block-is-invalid)

**Comment by RyanLucchese** [comment]
Fixes #70

**Pull request merged**
